
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[432] =
    {   0,
        0,    0,   52,   50,   48,   49,   50,   50,   23,   24,
       47,   42,   42,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,    0,   43,    0,   42,    0,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,    0,   45,   45,   18,   45,
       45,   45,   45,   45,    0,   45,   45,   45,   45,   45,
       45,   45,    0,   45,   45,   45,   45,   45,   45,   44,
        0,    0,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,    2,   45,   45,    0,    0,

        0,    0,    0,    0,   31,   45,   45,   45,    0,   39,
       45,    0,   45,   45,   45,   45,   45,   45,   45,    0,
       45,    0,    0,    0,   45,   45,    0,    0,    0,   45,
        7,   45,    0,   45,   45,   45,   45,   45,   45,   19,
       45,    2,    2,    2,   20,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   45,   45,   45,    0,   45,    0,
       45,   45,   38,   45,   45,    0,    0,   45,    0,    0,
        0,   45,   45,   46,    0,    0,   38,    0,    0,   45,
       45,   45,    0,   45,   45,   45,    2,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   45,   45,

        0,    0,   45,    0,    0,   45,    0,   45,   45,    0,
        0,    0,    0,    0,    0,   45,   45,    0,   39,   45,
        0,    0,   45,   45,    8,    0,   45,   45,    2,    0,
        0,    6,    0,    0,    0,    0,    0,    0,    0,    0,
       45,    0,    0,   30,    0,    0,   45,    0,   38,   45,
       32,    0,    0,   28,    0,    0,   45,   45,    0,    0,
        0,   45,   40,   33,    0,    0,    2,    0,    0,    0,
        0,    0,    0,    0,   22,    0,    0,   45,    0,   36,
        0,    0,   45,    0,   45,   45,    0,    0,    0,    0,
       10,    0,    0,    0,   45,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   46,   29,    0,    0,    0,
        0,    0,   45,    0,   21,    0,    0,    0,   37,    4,
       35,   15,    0,    0,    0,    0,    0,    0,    0,    0,
       17,    0,    0,    0,    0,   45,   41,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    1,    0,   34,    0,
        0,    9,    0,    0,    0,   11,    0,    0,    0,    0,
        0,   27,    0,    0,    0,    0,    0,   12,    5,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       38,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   16,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   25,    0,    0,    0,    0,   26,    0,    3,
        0,    0,    0,    0,    0,    0,    0,    0,   13,   14,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    7,    8,
        9,    1,    1,    1,    1,   10,    1,   11,   12,   13,
       13,   13,   13,   13,   13,   13,   13,    1,   14,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
        1,    1,    1,    1,    1,    1,   41,   31,   42,   31,

       43,   44,   31,   31,   45,   31,   31,   46,   31,   31,
       47,   31,   31,   48,   31,   49,   50,   51,   31,   31,
       52,   31,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[53] =
    {   0,
        1,    1,    2,    3,    1,    3,    1,    1,    1,    4,
        5,    5,    5,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5
    } ;

static const flex_int16_t yy_base[439] =
    {   0,
        0,    0,  676,  677,  677,  677,  669,    0,  677,  677,
      677,  677,   42,   46,   47,   49,   52,   54,   53,  664,
       51,   79,   48,   72,   55,   83,   62,   87,   50,   94,
       86,   97,   75,   78,  667,  677,  665,  116,  625,  660,
      107,   85,   89,  105,  115,  120,   93,  108,  123,  126,
      128,  132,  130,  131,  134,  130,  142,  144,  659,  137,
      139,  147,  158,  153,  645,  160,  154,  162,  163,  164,
      167,  172,  650,  176,  181,  185,  186,  156,  177,  677,
      619,  643,  193,  178,  188,  190,  198,  194,  195,  196,
      197,  199,  203,  205,  206,  251,  208,  219,  637,  640,

      643,  642,  205,  637,  220,  222,  224,  225,  622,  648,
      226,  624,  210,  228,  227,  237,  233,  258,  238,  641,
      254,  623,  639,  636,  229,  231,  606,  636,  621,  256,
      639,  267,  621,  259,  260,  263,  274,  269,  272,  637,
      275,    0,  600,  309,  635,  621,  603,  606,  626,  621,
      611,  619,  597,  608,  323,  276,  286,  620,  279,  630,
      289,  287,  290,  282,  297,  604,  604,  302,  605,  603,
      614,  291,  292,  677,  592,  607,  293,  597,  610,  325,
      324,  311,  595,  326,  328,  330,  576,  582,  617,  601,
      583,  600,  613,  601,  611,  595,  579,  309,  369,  343,

      583,  588,  334,  587,  575,  339,  593,  336,  338,  587,
      602,  582,  565,  599,  574,  341,  344,  578,  677,  353,
      580,  565,  348,  352,  588,  577,  355,  377,  550,  591,
      577,  677,  589,  559,  552,  554,  566,  551,  359,  350,
      561,  563,  565,  677,  550,  561,  378,  554,  384,  376,
      677,  548,  546,  677,  544,  574,   57,  354,  549,  547,
      556,  380,  564,  677,  544,  543,    0,  548,  544,  552,
      564,  535,  543,  561,  677,  377,  364,  550,  530,  677,
      558,  542,  397,  556,  398,  390,  540,  518,  524,  534,
      545,  550,  533,  547,  399,  531,  530,  545,  533,  521,

      512,  541,  516,  524,  394,  508,  677,  509,  512,  510,
      397,  509,  404,  518,  677,  513,  520,  506,  677,  677,
      677,  677,  500,  517,  509,  504,  525,  501,  383,  501,
      677,  506,  502,  497,  503,  406,  677,  494,  485,  501,
      486,  485,  494,  487,  481,  484,  479,  473,  677,  490,
      495,  499,  487,  503,  469,  677,  472,  471,  474,  480,
      472,  677,  479,  473,  494,  463,  492,  677,  677,  465,
      471,  461,  460,  465,  463,  467,  459,  447,  453,  451,
      677,  452,  464,  459,  465,  476,  475,  463,  450,  443,
      451,  437,  447,  444,  452,  677,  438,  429,  418,  410,

      426,  425,  415,  411,  435,  409,  403,  416,  404,  413,
      414,  425,  677,  387,  391,  406,  407,  677,  395,  677,
      407,  404,  394,  386,  392,  332,  286,  222,  677,  677,
      677,  443,  145,  445,  450,  455,  460,  465
    } ;

static const flex_int16_t yy_def[439] =
    {   0,
      431,    1,  431,  431,  431,  431,  432,  433,  431,  431,
      431,  431,  431,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  432,  431,  431,  431,  431,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  431,  434,  434,  434,  434,
      434,  434,  434,  434,  431,  434,  434,  434,  434,  434,
      434,  434,  431,  434,  434,  434,  434,  434,  434,  431,
      431,  431,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  435,  434,  434,  431,  431,

      431,  431,  431,  431,  434,  434,  434,  434,  431,  434,
      434,  431,  434,  434,  434,  434,  434,  434,  434,  431,
      434,  431,  431,  431,  434,  434,  431,  431,  431,  434,
      434,  434,  431,  434,  434,  434,  434,  434,  434,  434,
      434,  436,  436,  435,  434,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  437,  434,  434,  431,  434,  431,
      434,  434,  434,  434,  434,  431,  431,  434,  431,  431,
      431,  434,  434,  431,  431,  431,  434,  431,  431,  434,
      434,  434,  431,  434,  434,  434,  436,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  438,  438,  437,  434,

      431,  431,  434,  431,  431,  434,  431,  434,  434,  431,
      431,  431,  431,  431,  431,  434,  434,  431,  431,  434,
      431,  431,  434,  434,  434,  431,  434,  434,  436,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  438,  438,
      199,  431,  431,  431,  431,  431,  434,  431,  434,  434,
      431,  431,  431,  431,  431,  431,  434,  434,  431,  431,
      431,  434,  434,  431,  431,  431,  436,  431,  431,  431,
      431,  431,  431,  431,  431,  438,  438,  199,  431,  431,
      431,  431,  434,  431,  434,  434,  431,  431,  431,  431,
      434,  431,  431,  431,  434,  431,  431,  431,  431,  431,

      431,  431,  431,  431,  438,  438,  431,  431,  431,  431,
      431,  431,  434,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  438,  431,
      431,  431,  431,  431,  431,  434,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  438,  431,  431,  431,
      431,  434,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,

      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
        0,  431,  431,  431,  431,  431,  431,  431
    } ;

static const flex_int16_t yy_nxt[730] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       12,   13,   13,    4,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   20,   20,   24,   25,   26,   27,
       20,   20,   28,   29,   30,   20,   31,   20,   32,   20,
       20,   20,   20,   33,   20,   20,   20,   20,   20,   20,
       34,   20,   38,   38,   38,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   54,   39,   60,   72,   43,
       46,   39,   41,   42,   49,   44,   50,   47,   52,   55,
       48,   39,   56,   63,   39,   45,   65,   39,   39,   64,
       61,   53,   39,   67,   39,   39,   39,   73,   39,  291,

       62,   68,   39,   39,   51,   57,   39,   66,   74,   84,
       82,   75,   58,   69,   39,   78,   39,   39,   59,   89,
       70,   71,   79,   83,   39,   76,   38,   38,   38,   39,
       85,   77,   39,   87,   88,   39,   90,   39,   86,   39,
       39,   39,   91,   39,   99,  103,   39,  104,   39,   37,
      100,   39,   96,   39,  107,  101,   39,  102,   92,   93,
       95,  109,   39,   39,  108,   39,   97,   39,   94,   39,
       98,   39,   39,   39,  113,  106,   39,  116,  117,  111,
      115,   39,  114,  105,  122,   39,   39,   39,  123,  124,
       39,  110,  121,  118,   39,   39,  129,   39,  130,   39,

      125,  133,   39,   39,   39,   39,   39,   39,   39,  119,
      135,  132,   39,  131,   39,   39,  137,   39,  126,   39,
      141,  138,  146,  154,  139,  134,  145,  151,   39,   39,
      152,   39,  136,   39,   39,   39,   39,   39,   39,  156,
       39,  159,   39,  157,  155,  162,   39,   39,  161,  430,
      140,  142,  142,  163,  142,  142,  142,  142,  142,  142,
      143,  166,  164,   39,  142,   39,  165,   39,   39,   39,
      178,  131,   39,  180,  172,  168,   39,  183,   39,  173,
      182,   39,  181,   39,   39,   39,  184,  177,   39,  201,
      185,   39,  205,  207,  200,   39,   39,  203,   39,   39,

       39,   39,   39,  429,  220,  212,   39,  208,  186,  142,
      142,   39,  142,  142,  142,  142,  142,  142,  143,  209,
       39,  206,  142,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  198,   39,   39,   39,  197,   39,  217,   39,
      216,  223,  239,   39,  227,   39,  242,   39,   39,  225,
       39,  224,   39,   39,  240,  247,  260,   39,  265,  228,
      428,   39,   39,   39,   39,  131,  250,  249,  131,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  198,  263,
      266,  262,  197,  239,  276,   39,   39,   39,  257,   39,
      305,  258,  239,   39,  283,  285,  277,  239,  295,   39,

      310,  312,  241,  286,  313,  291,   39,   39,   39,  306,
      239,  329,  333,   39,  347,   39,  239,  427,  426,  425,
      424,  423,  422,  421,  420,  419,  418,  239,  417,  334,
      131,  416,  415,  414,  413,  336,  412,  411,  410,  409,
      408,  407,  406,  405,  352,   35,  404,   35,   40,   40,
      144,  403,  144,  144,  144,  142,  402,  142,  142,  142,
      199,  199,  199,  199,  199,  197,  197,  197,  197,  197,
      401,  400,  399,  398,  397,  396,  395,  394,  393,  392,
      391,  390,  389,  381,  388,  387,  386,  385,  384,  383,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,

      372,  371,  370,  369,  368,  367,  366,  365,   39,  364,
      363,  362,  239,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  319,  351,  350,  349,  348,  346,  345,  344,
      343,  342,  341,  340,  339,  338,  337,  335,  332,  331,
      330,  239,  328,  327,  326,  325,  324,  323,  322,  219,
      321,  320,  319,  318,   39,  317,  316,  315,  314,  311,
      309,  308,  307,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,   39,  294,  293,  292,  290,  289,  288,
      287,  284,  282,  281,  280,  279,  278,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  264,   39,  261,  219,

      259,  256,  255,  254,  253,  252,  251,  248,  246,  245,
      244,  243,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  226,  222,  221,  219,  218,  215,  214,
      213,  211,  210,  204,  202,  196,  195,  194,  193,  192,
      191,  190,  189,  188,   39,  187,   39,  179,   39,  176,
      175,  174,  171,  170,  169,  167,  160,   39,  158,  153,
      150,  149,  148,  147,  128,  127,  120,  112,   39,   39,
       81,   80,   36,   39,   36,  431,    3,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,

      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431
    } ;

static const flex_int16_t yy_chk[730] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   13,   13,   13,   14,   15,   23,   16,   29,
       21,   17,   19,   18,   25,   21,  257,   23,   29,   15,
       16,   27,   14,   14,   17,   15,   18,   16,   19,   21,
       16,   24,   22,   25,   33,   15,   26,   34,   22,   25,
       24,   19,   26,   27,   42,   31,   28,   30,   43,  257,

       24,   28,   47,   30,   18,   22,   32,   26,   31,   43,
       41,   32,   22,   28,   44,   33,   41,   48,   22,   47,
       28,   28,   34,   42,   45,   32,   38,   38,   38,   46,
       44,   32,   49,   45,   46,   50,   48,   51,   44,   53,
       54,   52,   49,   55,   56,   57,   60,   58,   61,  433,
       56,   57,   53,   58,   61,   56,   62,   56,   49,   50,
       52,   63,   64,   67,   62,   78,   54,   63,   51,   66,
       55,   68,   69,   70,   66,   60,   71,   69,   70,   64,
       68,   72,   67,   58,   75,   74,   79,   84,   76,   77,
       75,   63,   74,   71,   76,   77,   83,   85,   84,   86,

       78,   87,   83,   88,   89,   90,   91,   87,   92,   72,
       89,   86,   93,   85,   94,   95,   91,   97,   79,  113,
       95,   92,   98,  105,   93,   88,   97,  103,   98,  105,
      103,  106,   90,  107,  108,  111,  115,  114,  125,  107,
      126,  111,  117,  108,  106,  114,  116,  119,  113,  428,
       94,   96,   96,  115,   96,   96,   96,   96,   96,   96,
       96,  118,  116,  121,   96,  130,  117,  118,  134,  135,
      132,  119,  136,  134,  125,  121,  132,  137,  138,  126,
      136,  139,  135,  137,  141,  156,  138,  130,  159,  157,
      139,  164,  161,  163,  156,  157,  162,  159,  161,  163,

      172,  173,  177,  427,  177,  168,  165,  164,  141,  144,
      144,  168,  144,  144,  144,  144,  144,  144,  144,  165,
      182,  162,  144,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  181,  180,  184,  155,  185,  173,  186,
      172,  180,  198,  203,  184,  208,  200,  209,  206,  182,
      216,  181,  200,  217,  198,  206,  220,  223,  227,  185,
      426,  224,  220,  258,  227,  203,  209,  208,  186,  199,
      199,  199,  199,  199,  199,  199,  199,  199,  199,  224,
      228,  223,  199,  240,  239,  250,  228,  247,  216,  262,
      276,  217,  239,  249,  247,  249,  240,  277,  262,  286,

      283,  285,  199,  250,  286,  258,  283,  285,  295,  277,
      276,  305,  311,  313,  329,  336,  329,  425,  424,  423,
      422,  421,  419,  417,  416,  415,  414,  305,  412,  311,
      295,  411,  410,  409,  408,  313,  407,  406,  405,  404,
      403,  402,  401,  400,  336,  432,  399,  432,  434,  434,
      435,  398,  435,  435,  435,  436,  397,  436,  436,  436,
      437,  437,  437,  437,  437,  438,  438,  438,  438,  438,
      395,  394,  393,  392,  391,  390,  389,  388,  387,  386,
      385,  384,  383,  382,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  371,  370,  367,  366,  365,  364,  363,

      361,  360,  359,  358,  357,  355,  354,  353,  352,  351,
      350,  348,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  335,  334,  333,  332,  330,  328,  327,  326,
      325,  324,  323,  318,  317,  316,  314,  312,  310,  309,
      308,  306,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  294,  293,  292,  291,  290,  289,  288,  287,  284,
      282,  281,  279,  278,  274,  273,  272,  271,  270,  269,
      268,  266,  265,  263,  261,  260,  259,  256,  255,  253,
      252,  248,  246,  245,  243,  242,  241,  238,  237,  236,
      235,  234,  233,  231,  230,  229,  226,  225,  222,  221,

      218,  215,  214,  213,  212,  211,  210,  207,  205,  204,
      202,  201,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  183,  179,  178,  176,  175,  171,  170,
      169,  167,  166,  160,  158,  154,  153,  152,  151,  150,
      149,  148,  147,  146,  145,  143,  140,  133,  131,  129,
      128,  127,  124,  123,  122,  120,  112,  110,  109,  104,
      102,  101,  100,   99,   82,   81,   73,   65,   59,   40,
       39,   37,   35,   20,    7,    3,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,

      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431,  431,
      431,  431,  431,  431,  431,  431,  431,  431,  431
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "memecode.l"
#line 2 "memecode.l"

#include <stdio.h>
#include "y.tab.h"

#line 751 "lex.yy.c"
#define YY_NO_INPUT 1
#line 753 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 10 "memecode.l"


#line 971 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 432 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 677 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 12 "memecode.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 13 "memecode.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 15 "memecode.l"
{return FILEBEGIN;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 16 "memecode.l"
{return FILEEND;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 18 "memecode.l"
{return INCLLINE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "memecode.l"
{yylval.string=strdup(yytext);return DECLARATION;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "memecode.l"
{yylval.string=strdup(yytext);return TYPE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 23 "memecode.l"
{return ARRAY;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 24 "memecode.l"
{return CONST;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 25 "memecode.l"
{return BINARY;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 27 "memecode.l"
{return CLASSBGN;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 28 "memecode.l"
{return CLASSEND;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "memecode.l"
{return OBJBGN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "memecode.l"
{return MFUNCBGN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 "memecode.l"
{return FUNCBGN;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "memecode.l"
{return FUNCRETURN;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "memecode.l"
{return FUNCEND;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "memecode.l"
{return FUNCCALL;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "memecode.l"
{return EVAL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "memecode.l"
{return OBJDECL;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "memecode.l"
{return OBJINITTYPE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "memecode.l"
{return NEWOBJVAL;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 45 "memecode.l"
{return POPEN;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 46 "memecode.l"
{return PCLOSE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "memecode.l"
{return WHILEBGN;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "memecode.l"
{return WHILEEND;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 53 "memecode.l"
{return IFSTMT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 54 "memecode.l"
{return IFCORRECT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "memecode.l"
{return ELSEIF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "memecode.l"
{return ELSE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "memecode.l"
{return ASSIGN;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "memecode.l"
{return SUM;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "memecode.l"
{return DIFF;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "memecode.l"
{return MUL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "memecode.l"
{return DIV;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "memecode.l"
{return MOD;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "memecode.l"
{return ARITH;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 67 "memecode.l"
{return COMPARISON;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 69 "memecode.l"
{return BOOL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 71 "memecode.l"
{return STRINGF;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 73 "memecode.l"
{return OUTPUT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "memecode.l"
{yylval.num=atoi(yytext);return NR;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 "memecode.l"
{yylval.string=strdup(yytext);return STRING;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "memecode.l"
{yylval.string=strdup(yytext);return CHAR;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "memecode.l"
{yylval.string=strdup(yytext);return ID;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 81 "memecode.l"
{return INCLUDE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "memecode.l"
{return ENDLINE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 85 "memecode.l"
;
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 86 "memecode.l"
{yylineno++;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 87 "memecode.l"
{return yytext[0];}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 90 "memecode.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1285 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 432 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 432 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 431);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 90 "memecode.l"
